name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies 
        run: npm install  
      - name: Check style        
        run: npm run eslint
      - name: Run npm test      
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Run npm build    
        run: npm run build

  deploy:
    needs: build_and_test
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  notify_success:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Discord deployment success
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: Success
          title: New version deployed
          description: | 
            commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Job: ${{ github.job }}

  notify_failure:
    needs: [build_and_test, deploy]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Discord deployment failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: Failure
          title: Deployment failure
          description: | 
            commit: ${{ github.sha }}
            Message: ${{ github.event.commits.*.message }}
            Author: ${{ github.actor }}
            Job: ${{ github.job }}
            Workflow: ${{ github.workflow }}

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch